[package]
org = "wso2healthcare"
name = "ObservationAPI"
version = "0.2.1"
export = ["ObservationAPI"]
distribution = "2201.3.1"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Observation","r4","international"]

[build-options]
observabilityIncluded = true
