[package]
org = "wso2healthcare"
name = "OrganizationAPI"
version = "0.2.1"
export = ["OrganizationAPI"]
distribution = "2201.3.1"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Organization","r4","international"]

[build-options]
observabilityIncluded = true
