[package]
org = "wso2healthcare"
name = "EncounterAPI"
version = "0.2.1"
export = ["EncounterAPI"]
distribution = "2201.3.1"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Encounter","r4","international"]

[build-options]
observabilityIncluded = true
