[package]
org = "wso2healthcare"
name = "PractitionerAPI"
version = "0.2.1"
export = ["PractitionerAPI"]
distribution = "2201.3.1"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Practitioner","r4","international"]

[build-options]
observabilityIncluded = true
